CREATE TABLE IF NOT EXISTS main_table (
	invoice_number integer Primary Key,
	"date" date,
	store_number integer ,
	store_name varchar,
	address varchar,
	city varchar,
	zip_code varchar,
	store_location varchar,
	county_number integer,
	county varchar,
	category integer,
	category_name varchar,
	vendor_number int,
	vendor_name varchar,
	item_number int,
	item_description varchar,
	pack integer,
	bottle_volume integer,
	state_bottle_cost varchar,
	state_bottle_retail varchar,
	bottles_sold int,
	sale_dollars varchar,
	volume_sold_liters numeric,
	volume_sold_gallons numeric
);